odecov:
  notify:
    require_ci_to_pass: true
  branch: main

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 0.5

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

github_checks:
  annotations: true

ignore:
  - "app/src/main/res/values*/*"