on: [pull_request]

jobs:
  add_pr_comment:
    permissions: write-all
    runs-on: ubuntu-latest
    name: OpenAI PR Comment
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - id: diff
        run: |
          git fetch origin main
          diff=$(git diff origin/main)
          echo $diff
          echo "DIFF=$(echo $diff)" >> $GITHUB_ENV
      - id: review
        uses: mono-chrome/GPTReviewWorkflow@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_KEY: ${{ secrets.OPENAI_ORG_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          REPOSITORY_NAME: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DIFF: ${{ env.DIFF }}
