name: Generate Android Release Notes
on: pull_request

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate release notes
        id: release_notes
        run: |
          echo "## Release Notes" >> release_notes.md
          git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" >> release_notes.md
          echo "${{ steps.release_notes.outputs.release_notes }}" # This outputs the release notes as an environment variable

      - name: Save release notes
        run: |
          echo "${{ steps.release_notes.outputs.release_notes }}" > release_notes.txt
          cat release_notes.txt # This displays the release notes in the GitHub Actions console
