name: Generate Release Notes

on:
  pull_request_target:
    types: [ closed ]
    branches: [ 'main' ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: check branch
        if: github.event.pull_request.merged == true && github.base_ref == 'main'
        run: echo ${{ github.head_ref }}

  release-notes:
    runs-on: ubuntu-latest
    needs: [ check-branch ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get Version
        id: get_version
        run: echo "::set-output name=version::v0.67-RC"

      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml 
	  version: ${{ steps.get_version.outputs.version }}
	  tag: ${{ steps.get_version.outputs.version }}
   
      - name: Create PR
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -d '{ "title": "${{ steps.get_tags.outputs.latest_tag }} Automated PR", "body": "version : ${{ steps.get_tags.outputs.latest_tag }}\nAutomatically generated PR", "head": "'main'", "base": "develop" }' \
               "https://api.github.com/repos/${{ github.repository }}/pulls"
