name: Generate Release Notes

on:
  pull_request_target:
    types: [ closed, edited ]
    branches: [ 'main' ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: check branch
        if: github.event.pull_request.merged == true && github.base_ref == 'main'
        run: echo ${{ github.head_ref }}

  release-notes:
    runs-on: ubuntu-latest
    needs: [ check-branch ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
