name: Measure coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Module Coverage
        run: ./gradlew jacocoTest

      - name: copy
        run: mkdir jacoco & cp ${{ github.workspace }}/app/build/reports/jacoco/jacocoTest/jacocoTest.xml jacoco/

      - name: Monitor coverage
        if: ! contains(github.event.pull_request.user.login, 'dependabot[bot]')
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "${{ github.workspace }}/jacoco/jacocoTest.xml"
